language: cpp
compiler:
- gcc

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
- sudo apt-get update

install:
- scripts/get-cmake.sh
- sudo apt-get -y -qq install libasio-dev gcc-4.9

before_script:
- echo "CMake has version $(cmake --version)"
- mkdir build && cd build
- cmake ..

script:
- make all
- cd test && ctest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e49314825582789cb40c
    on_success: change
    on_failure: always
    on_start: false
