language: cpp
compiler:
- gcc

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
- sudo apt-get update

install:
- scripts/get-cmake.sh
- sudo apt-get -y -qq install libasio-dev gcc-4.9

after_install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_script:
- echo "$(cmake --version)
        $(gcc --version)
        "
- mkdir build && cd build
- cmake ..

script:
- make all
- cd test && ctest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bce99bff09d11703eff7
    on_success: change
    on_failure: always
    on_start: false
