language: cpp
compiler:
- gcc
- clang

install:
- sudo apt-get install libasio-dev

before_script:
- mkdir build && cd build
- cmake ..

script:
- make
- make test
- cd test && ctest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e49314825582789cb40c
    on_success: change
    on_failure: always
    on_start: false
