language: cpp
compiler:
- gcc

install:
- scripts/get-cmake.sh
- sudo apt-get install libasio-dev

before_script:
- mkdir build && cd build
- cmake ..

script:
- make all
- cd test && ctest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e49314825582789cb40c
    on_success: change
    on_failure: always
    on_start: false
